# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eliot's Website
author: Eliot Lash
email: fadookie@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Portfolio (games, interactive art, live music visuals, etc.) and blog of Eliot Lash.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fadookie
youtube_url: https://www.youtube.com/@EliotLash
youtube_username: '@EliotLash'
mastodon_url: https://social.coop/@Eliot_L
mastodon_username: '@Eliot.L@social.coop'
itchio_url: https://eliot-l.itch.io
itchio_username: 'eliot-l'
permalink: /:year/:month/:title/

collections:
  works:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Silence deprecation warnings from minima theme per https://github.com/jekyll/minima/issues/709#issuecomment-1439967963
sass:
  quiet_deps: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
